USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id

dataset: ml-20m
load_col:
    inter: [user_id, item_id, timestamp]

train_neg_sample_args:
  
   
device: cuda:0
MAX_ITEM_LIST_LENGTH: 50
learning_rate: 1e-4
train_batch_size: 6000
eval_batch_size: 6000
mask_ratio: 0.2
hidden_size: 128
inner_size: 512
n_layers: 8
n_heads: 4
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'

model: STRec
topk: 10
metrics: ['Hit', 'MRR', 'NDCG']
valid_metric: 'NDCG@10'
eval_args: {'split': {'RS': [0.8,0.2,0.1]}, 'order': 'TO', 'mode': 'full', 'group_by': 'user'}
stopping_step: 3
eval_step: 3

mode: 'speed'
load_dir: 'saved/STRec.pth'
epochs: 500
pre_file: 'saved/.pth'
hash: 'False'
